[build]
  command = "npm install --force && export CI=false && npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "src/index.js"
  status = 200

[functions]
  directory = "functions"