[build]
command = "npm install --force && export CI=false && npm run build"
publish = "build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/src/index.js"
  status = 200
